-- 뚠뚠팀 v38 LIVE 통합 SQL
-- 기존 v37.1 분배금 테이블 보장 + v38 영구 저장/편지 DB를 한 번에 구성합니다.
-- 기존 데이터는 DROP하지 않습니다.

-- v37.1: distribution DB repair + category-independent live storage
-- IMPORTANT: the existing app uses text IDs for clans and clan_id values such as 'ddunteam'.
-- This migration intentionally uses TEXT for clan_id/member_id to avoid type-mismatch FK failures.

create table if not exists public.clan_distribution_settings (
  clan_id text primary key,
  diamond bigint not null default 0,
  notes text not null default '',
  updated_at timestamptz not null default now(),
  updated_by_user_id uuid,
  updated_by_nickname text
);

create table if not exists public.clan_distribution_payments (
  id bigint generated by default as identity primary key,
  clan_id text not null,
  member_id text,
  nickname text not null,
  amount bigint not null default 0,
  paid boolean not null default false,
  paid_at timestamptz,
  paid_by_user_id uuid,
  paid_by_nickname text,
  note text not null default '',
  time_class text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (clan_id, member_id)
);

create index if not exists clan_distribution_payments_clan_idx
  on public.clan_distribution_payments(clan_id);

create index if not exists clan_distribution_payments_member_idx
  on public.clan_distribution_payments(member_id);

grant usage on schema public to authenticated;
grant select, insert, update on public.clan_distribution_settings to authenticated;
grant select, insert, update on public.clan_distribution_payments to authenticated;

alter table public.clan_distribution_settings enable row level security;
alter table public.clan_distribution_payments enable row level security;

drop policy if exists "distribution_settings_select_manage" on public.clan_distribution_settings;
create policy "distribution_settings_select_manage"
on public.clan_distribution_settings for select to authenticated
using (
  exists (
    select 1 from public.clans c
    where c.id::text = clan_distribution_settings.clan_id
      and (
        c.owner_user_id = auth.uid()
        or exists (
          select 1 from public.clan_members m
          where m.clan_id::text = c.id::text
            and m.user_id = auth.uid()
            and m.role = '군주'
        )
      )
  )
);

drop policy if exists "distribution_settings_insert_manage" on public.clan_distribution_settings;
create policy "distribution_settings_insert_manage"
on public.clan_distribution_settings for insert to authenticated
with check (
  exists (
    select 1 from public.clans c
    where c.id::text = clan_distribution_settings.clan_id
      and (
        c.owner_user_id = auth.uid()
        or exists (
          select 1 from public.clan_members m
          where m.clan_id::text = c.id::text
            and m.user_id = auth.uid()
            and m.role = '군주'
        )
      )
  )
);

drop policy if exists "distribution_settings_update_manage" on public.clan_distribution_settings;
create policy "distribution_settings_update_manage"
on public.clan_distribution_settings for update to authenticated
using (
  exists (
    select 1 from public.clans c
    where c.id::text = clan_distribution_settings.clan_id
      and (
        c.owner_user_id = auth.uid()
        or exists (
          select 1 from public.clan_members m
          where m.clan_id::text = c.id::text
            and m.user_id = auth.uid()
            and m.role = '군주'
        )
      )
  )
)
with check (
  exists (
    select 1 from public.clans c
    where c.id::text = clan_distribution_settings.clan_id
      and (
        c.owner_user_id = auth.uid()
        or exists (
          select 1 from public.clan_members m
          where m.clan_id::text = c.id::text
            and m.user_id = auth.uid()
            and m.role = '군주'
        )
      )
  )
);

drop policy if exists "distribution_payments_select_manage" on public.clan_distribution_payments;
create policy "distribution_payments_select_manage"
on public.clan_distribution_payments for select to authenticated
using (
  exists (
    select 1 from public.clans c
    where c.id::text = clan_distribution_payments.clan_id
      and (
        c.owner_user_id = auth.uid()
        or exists (
          select 1 from public.clan_members m
          where m.clan_id::text = c.id::text
            and m.user_id = auth.uid()
            and m.role = '군주'
        )
      )
  )
);

drop policy if exists "distribution_payments_insert_manage" on public.clan_distribution_payments;
create policy "distribution_payments_insert_manage"
on public.clan_distribution_payments for insert to authenticated
with check (
  exists (
    select 1 from public.clans c
    where c.id::text = clan_distribution_payments.clan_id
      and (
        c.owner_user_id = auth.uid()
        or exists (
          select 1 from public.clan_members m
          where m.clan_id::text = c.id::text
            and m.user_id = auth.uid()
            and m.role = '군주'
        )
      )
  )
);

drop policy if exists "distribution_payments_update_manage" on public.clan_distribution_payments;
create policy "distribution_payments_update_manage"
on public.clan_distribution_payments for update to authenticated
using (
  exists (
    select 1 from public.clans c
    where c.id::text = clan_distribution_payments.clan_id
      and (
        c.owner_user_id = auth.uid()
        or exists (
          select 1 from public.clan_members m
          where m.clan_id::text = c.id::text
            and m.user_id = auth.uid()
            and m.role = '군주'
        )
      )
  )
)
with check (
  exists (
    select 1 from public.clans c
    where c.id::text = clan_distribution_payments.clan_id
      and (
        c.owner_user_id = auth.uid()
        or exists (
          select 1 from public.clan_members m
          where m.clan_id::text = c.id::text
            and m.user_id = auth.uid()
            and m.role = '군주'
        )
      )
  )
);

-- Enable realtime for live payment-status refreshes. Safe if already enabled.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime'
      and schemaname='public'
      and tablename='clan_distribution_payments'
  ) then
    execute 'alter publication supabase_realtime add table public.clan_distribution_payments';
  end if;
end $$;




-- 뚠뚠팀 v38 LIVE DATA FIX
-- 기존 테이블/데이터를 삭제하지 않습니다.
-- 1) SQL Editor에서 전체 실행
-- 2) 마지막 NOTIFY까지 실행

create table if not exists public.clan_private_state (
  id bigint generated by default as identity primary key,
  clan_id text not null,
  state_key text not null,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  updated_by_nickname text,
  unique (clan_id, state_key)
);

create table if not exists public.clan_letters (
  id bigint generated by default as identity primary key,
  clan_id text not null,
  status text not null default '대기중',
  anonymous boolean not null default false,
  author_nickname text not null default '알 수 없음',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.clan_letter_bodies (
  id bigint primary key references public.clan_letters(id) on delete cascade,
  clan_id text not null,
  title text not null default '',
  body text not null default '',
  comments jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

create index if not exists idx_clan_private_state_clan on public.clan_private_state(clan_id);
create index if not exists idx_clan_letters_clan_created on public.clan_letters(clan_id, created_at desc);
create index if not exists idx_clan_letter_bodies_clan on public.clan_letter_bodies(clan_id);

grant usage on schema public to authenticated;
grant select, insert, update, delete on public.clan_private_state to authenticated;
grant select, insert, update, delete on public.clan_letters to authenticated;
grant select, insert, update, delete on public.clan_letter_bodies to authenticated;
grant usage, select on all sequences in schema public to authenticated;

alter table public.clan_private_state enable row level security;
alter table public.clan_letters enable row level security;
alter table public.clan_letter_bodies enable row level security;

-- Re-runnable policies
 drop policy if exists "v38 private state select" on public.clan_private_state;
 drop policy if exists "v38 private state insert" on public.clan_private_state;
 drop policy if exists "v38 private state update" on public.clan_private_state;
 drop policy if exists "v38 private state delete" on public.clan_private_state;
 drop policy if exists "v38 letters select" on public.clan_letters;
 drop policy if exists "v38 letters insert" on public.clan_letters;
 drop policy if exists "v38 letters update" on public.clan_letters;
 drop policy if exists "v38 letters delete" on public.clan_letters;
 drop policy if exists "v38 letter bodies select" on public.clan_letter_bodies;
 drop policy if exists "v38 letter bodies insert" on public.clan_letter_bodies;
 drop policy if exists "v38 letter bodies update" on public.clan_letter_bodies;
 drop policy if exists "v38 letter bodies delete" on public.clan_letter_bodies;

-- 공통: 현재 로그인 사용자가 해당 혈맹의 구성원인지 확인
create policy "v38 private state select" on public.clan_private_state
for select to authenticated
using (
  (
    clan_private_state.state_key <> 'memo'
    and (
      exists (select 1 from public.clans c where c.id::text = clan_private_state.clan_id and c.owner_user_id = auth.uid())
      or exists (select 1 from public.clan_members m where m.clan_id::text = clan_private_state.clan_id and m.user_id = auth.uid())
    )
  )
  or (
    clan_private_state.state_key = 'memo'
    and (
      exists (select 1 from public.clans c where c.id::text = clan_private_state.clan_id and c.owner_user_id = auth.uid())
      or exists (select 1 from public.clan_members m where m.clan_id::text = clan_private_state.clan_id and m.user_id = auth.uid() and m.role = '군주')
    )
  )
);

create policy "v38 private state insert" on public.clan_private_state
for insert to authenticated
with check (
  (
    state_key = 'memo'
    and (
      exists (select 1 from public.clans c where c.id::text = clan_private_state.clan_id and c.owner_user_id = auth.uid())
      or exists (select 1 from public.clan_members m where m.clan_id::text = clan_private_state.clan_id and m.user_id = auth.uid() and m.role = '군주')
    )
  )
  or (
    state_key <> 'memo'
    and (
      exists (select 1 from public.clans c where c.id::text = clan_private_state.clan_id and c.owner_user_id = auth.uid())
      or exists (select 1 from public.clan_members m where m.clan_id::text = clan_private_state.clan_id and m.user_id = auth.uid() and m.role in ('군주','관리자','수호','일반'))
    )
  )
);

create policy "v38 private state update" on public.clan_private_state
for update to authenticated
using (
  (
    state_key = 'memo'
    and (
      exists (select 1 from public.clans c where c.id::text = clan_private_state.clan_id and c.owner_user_id = auth.uid())
      or exists (select 1 from public.clan_members m where m.clan_id::text = clan_private_state.clan_id and m.user_id = auth.uid() and m.role = '군주')
    )
  )
  or (
    state_key <> 'memo'
    and (
      exists (select 1 from public.clans c where c.id::text = clan_private_state.clan_id and c.owner_user_id = auth.uid())
      or exists (select 1 from public.clan_members m where m.clan_id::text = clan_private_state.clan_id and m.user_id = auth.uid() and m.role in ('군주','관리자'))
    )
  )
)
with check (true);

create policy "v38 private state delete" on public.clan_private_state
for delete to authenticated
using (
  exists (select 1 from public.clans c where c.id::text = clan_private_state.clan_id and c.owner_user_id = auth.uid())
  or exists (select 1 from public.clan_members m where m.clan_id::text = clan_private_state.clan_id and m.user_id = auth.uid() and m.role in ('군주','관리자'))
);

create policy "v38 letters select" on public.clan_letters
for select to authenticated
using (
  exists (select 1 from public.clans c where c.id::text = clan_letters.clan_id and c.owner_user_id = auth.uid())
  or exists (select 1 from public.clan_members m where m.clan_id::text = clan_letters.clan_id and m.user_id = auth.uid())
);

create policy "v38 letters insert" on public.clan_letters
for insert to authenticated
with check (
  exists (select 1 from public.clans c where c.id::text = clan_letters.clan_id and c.owner_user_id = auth.uid())
  or exists (select 1 from public.clan_members m where m.clan_id::text = clan_letters.clan_id and m.user_id = auth.uid())
);

create policy "v38 letters update" on public.clan_letters
for update to authenticated
using (
  exists (select 1 from public.clans c where c.id::text = clan_letters.clan_id and c.owner_user_id = auth.uid())
  or exists (select 1 from public.clan_members m where m.clan_id::text = clan_letters.clan_id and m.user_id = auth.uid() and m.role in ('군주','관리자','수호'))
)
with check (true);

create policy "v38 letters delete" on public.clan_letters
for delete to authenticated
using (
  exists (select 1 from public.clans c where c.id::text = clan_letters.clan_id and c.owner_user_id = auth.uid())
  or exists (select 1 from public.clan_members m where m.clan_id::text = clan_letters.clan_id and m.user_id = auth.uid() and m.role in ('군주','관리자','수호'))
);

-- 본문은 관리진만 SELECT 가능. INSERT는 일반 혈맹원도 가능하여 비밀 편지 작성이 가능함.
create policy "v38 letter bodies select" on public.clan_letter_bodies
for select to authenticated
using (
  exists (select 1 from public.clans c where c.id::text = clan_letter_bodies.clan_id and c.owner_user_id = auth.uid())
  or exists (select 1 from public.clan_members m where m.clan_id::text = clan_letter_bodies.clan_id and m.user_id = auth.uid() and m.role in ('군주','관리자','수호'))
);

create policy "v38 letter bodies insert" on public.clan_letter_bodies
for insert to authenticated
with check (
  exists (select 1 from public.clans c where c.id::text = clan_letter_bodies.clan_id and c.owner_user_id = auth.uid())
  or exists (select 1 from public.clan_members m where m.clan_id::text = clan_letter_bodies.clan_id and m.user_id = auth.uid())
);

create policy "v38 letter bodies update" on public.clan_letter_bodies
for update to authenticated
using (
  exists (select 1 from public.clans c where c.id::text = clan_letter_bodies.clan_id and c.owner_user_id = auth.uid())
  or exists (select 1 from public.clan_members m where m.clan_id::text = clan_letter_bodies.clan_id and m.user_id = auth.uid() and m.role in ('군주','관리자','수호'))
)
with check (true);

create policy "v38 letter bodies delete" on public.clan_letter_bodies
for delete to authenticated
using (
  exists (select 1 from public.clans c where c.id::text = clan_letter_bodies.clan_id and c.owner_user_id = auth.uid())
  or exists (select 1 from public.clan_members m where m.clan_id::text = clan_letter_bodies.clan_id and m.user_id = auth.uid() and m.role in ('군주','관리자','수호'))
);

-- 기존 분배금 테이블이 이미 있다면 그대로 사용하고, PostgREST 캐시만 갱신
notify pgrst, 'reload schema';
