-- v37.1: distribution DB repair + category-independent live storage
-- IMPORTANT: the existing app uses text IDs for clans and clan_id values such as 'ddunteam'.
-- This migration intentionally uses TEXT for clan_id/member_id to avoid type-mismatch FK failures.

create table if not exists public.clan_distribution_settings (
  clan_id text primary key,
  diamond bigint not null default 0,
  notes text not null default '',
  updated_at timestamptz not null default now(),
  updated_by_user_id uuid,
  updated_by_nickname text
);

create table if not exists public.clan_distribution_payments (
  id bigint generated by default as identity primary key,
  clan_id text not null,
  member_id text,
  nickname text not null,
  amount bigint not null default 0,
  paid boolean not null default false,
  paid_at timestamptz,
  paid_by_user_id uuid,
  paid_by_nickname text,
  note text not null default '',
  time_class text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (clan_id, member_id)
);

create index if not exists clan_distribution_payments_clan_idx
  on public.clan_distribution_payments(clan_id);

create index if not exists clan_distribution_payments_member_idx
  on public.clan_distribution_payments(member_id);

grant usage on schema public to authenticated;
grant select, insert, update on public.clan_distribution_settings to authenticated;
grant select, insert, update on public.clan_distribution_payments to authenticated;

alter table public.clan_distribution_settings enable row level security;
alter table public.clan_distribution_payments enable row level security;

drop policy if exists "distribution_settings_select_manage" on public.clan_distribution_settings;
create policy "distribution_settings_select_manage"
on public.clan_distribution_settings for select to authenticated
using (
  exists (
    select 1 from public.clans c
    where c.id::text = clan_distribution_settings.clan_id
      and (
        c.owner_user_id = auth.uid()
        or exists (
          select 1 from public.clan_members m
          where m.clan_id::text = c.id::text
            and m.user_id = auth.uid()
            and m.role = '군주'
        )
      )
  )
);

drop policy if exists "distribution_settings_insert_manage" on public.clan_distribution_settings;
create policy "distribution_settings_insert_manage"
on public.clan_distribution_settings for insert to authenticated
with check (
  exists (
    select 1 from public.clans c
    where c.id::text = clan_distribution_settings.clan_id
      and (
        c.owner_user_id = auth.uid()
        or exists (
          select 1 from public.clan_members m
          where m.clan_id::text = c.id::text
            and m.user_id = auth.uid()
            and m.role = '군주'
        )
      )
  )
);

drop policy if exists "distribution_settings_update_manage" on public.clan_distribution_settings;
create policy "distribution_settings_update_manage"
on public.clan_distribution_settings for update to authenticated
using (
  exists (
    select 1 from public.clans c
    where c.id::text = clan_distribution_settings.clan_id
      and (
        c.owner_user_id = auth.uid()
        or exists (
          select 1 from public.clan_members m
          where m.clan_id::text = c.id::text
            and m.user_id = auth.uid()
            and m.role = '군주'
        )
      )
  )
)
with check (
  exists (
    select 1 from public.clans c
    where c.id::text = clan_distribution_settings.clan_id
      and (
        c.owner_user_id = auth.uid()
        or exists (
          select 1 from public.clan_members m
          where m.clan_id::text = c.id::text
            and m.user_id = auth.uid()
            and m.role = '군주'
        )
      )
  )
);

drop policy if exists "distribution_payments_select_manage" on public.clan_distribution_payments;
create policy "distribution_payments_select_manage"
on public.clan_distribution_payments for select to authenticated
using (
  exists (
    select 1 from public.clans c
    where c.id::text = clan_distribution_payments.clan_id
      and (
        c.owner_user_id = auth.uid()
        or exists (
          select 1 from public.clan_members m
          where m.clan_id::text = c.id::text
            and m.user_id = auth.uid()
            and m.role = '군주'
        )
      )
  )
);

drop policy if exists "distribution_payments_insert_manage" on public.clan_distribution_payments;
create policy "distribution_payments_insert_manage"
on public.clan_distribution_payments for insert to authenticated
with check (
  exists (
    select 1 from public.clans c
    where c.id::text = clan_distribution_payments.clan_id
      and (
        c.owner_user_id = auth.uid()
        or exists (
          select 1 from public.clan_members m
          where m.clan_id::text = c.id::text
            and m.user_id = auth.uid()
            and m.role = '군주'
        )
      )
  )
);

drop policy if exists "distribution_payments_update_manage" on public.clan_distribution_payments;
create policy "distribution_payments_update_manage"
on public.clan_distribution_payments for update to authenticated
using (
  exists (
    select 1 from public.clans c
    where c.id::text = clan_distribution_payments.clan_id
      and (
        c.owner_user_id = auth.uid()
        or exists (
          select 1 from public.clan_members m
          where m.clan_id::text = c.id::text
            and m.user_id = auth.uid()
            and m.role = '군주'
        )
      )
  )
)
with check (
  exists (
    select 1 from public.clans c
    where c.id::text = clan_distribution_payments.clan_id
      and (
        c.owner_user_id = auth.uid()
        or exists (
          select 1 from public.clan_members m
          where m.clan_id::text = c.id::text
            and m.user_id = auth.uid()
            and m.role = '군주'
        )
      )
  )
);

-- Enable realtime for live payment-status refreshes. Safe if already enabled.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime'
      and schemaname='public'
      and tablename='clan_distribution_payments'
  ) then
    execute 'alter publication supabase_realtime add table public.clan_distribution_payments';
  end if;
end $$;

notify pgrst, 'reload schema';
