-- 뚠뚠팀 v39 LIVE FIX
-- IMPORTANT: 기존 데이터 DROP/TRUNCATE/DELETE 없음.
-- v36.53 안정 버전을 기준으로 분배금 기능만 서버 저장으로 연결합니다.
-- v37.1에서 이미 생성된 분배금 테이블이 있으면 그대로 재사용합니다.

create table if not exists public.clan_distribution_settings (
  clan_id text primary key,
  diamond bigint not null default 0,
  notes text not null default '',
  updated_at timestamptz not null default now(),
  updated_by_user_id uuid,
  updated_by_nickname text
);

create table if not exists public.clan_distribution_payments (
  id bigint generated by default as identity primary key,
  clan_id text not null,
  member_id text,
  nickname text not null,
  amount bigint not null default 0,
  paid boolean not null default false,
  paid_at timestamptz,
  paid_by_user_id uuid,
  paid_by_nickname text,
  note text not null default '',
  time_class text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (clan_id, member_id)
);

create index if not exists clan_distribution_payments_clan_idx
  on public.clan_distribution_payments(clan_id);

-- 2026년 Supabase Data API는 새 public 테이블을 명시적으로 노출/권한 부여해야 할 수 있습니다.
grant usage on schema public to authenticated;
grant select, insert, update on public.clan_distribution_settings to authenticated;
grant select, insert, update on public.clan_distribution_payments to authenticated;

grant usage, select on sequence public.clan_distribution_payments_id_seq to authenticated;

alter table public.clan_distribution_settings enable row level security;
alter table public.clan_distribution_payments enable row level security;

-- 기존 정책 이름이 있어도 안전하게 교체합니다. 데이터에는 영향을 주지 않습니다.
drop policy if exists "distribution_settings_select_manage" on public.clan_distribution_settings;
create policy "distribution_settings_select_manage"
on public.clan_distribution_settings for select to authenticated
using (
  exists (
    select 1 from public.clans c
    where c.id::text = clan_distribution_settings.clan_id
      and (
        c.owner_user_id = auth.uid()
        or exists (
          select 1 from public.clan_members m
          where m.clan_id::text = c.id::text
            and m.user_id = auth.uid()
            and m.role = '군주'
        )
      )
  )
);

drop policy if exists "distribution_settings_insert_manage" on public.clan_distribution_settings;
create policy "distribution_settings_insert_manage"
on public.clan_distribution_settings for insert to authenticated
with check (
  exists (
    select 1 from public.clans c
    where c.id::text = clan_distribution_settings.clan_id
      and (
        c.owner_user_id = auth.uid()
        or exists (
          select 1 from public.clan_members m
          where m.clan_id::text = c.id::text
            and m.user_id = auth.uid()
            and m.role = '군주'
        )
      )
  )
);

drop policy if exists "distribution_settings_update_manage" on public.clan_distribution_settings;
create policy "distribution_settings_update_manage"
on public.clan_distribution_settings for update to authenticated
using (
  exists (
    select 1 from public.clans c
    where c.id::text = clan_distribution_settings.clan_id
      and (
        c.owner_user_id = auth.uid()
        or exists (
          select 1 from public.clan_members m
          where m.clan_id::text = c.id::text
            and m.user_id = auth.uid()
            and m.role = '군주'
        )
      )
  )
)
with check (
  exists (
    select 1 from public.clans c
    where c.id::text = clan_distribution_settings.clan_id
      and (
        c.owner_user_id = auth.uid()
        or exists (
          select 1 from public.clan_members m
          where m.clan_id::text = c.id::text
            and m.user_id = auth.uid()
            and m.role = '군주'
        )
      )
  )
);

drop policy if exists "distribution_payments_select_manage" on public.clan_distribution_payments;
create policy "distribution_payments_select_manage"
on public.clan_distribution_payments for select to authenticated
using (
  exists (
    select 1 from public.clans c
    where c.id::text = clan_distribution_payments.clan_id
      and (
        c.owner_user_id = auth.uid()
        or exists (
          select 1 from public.clan_members m
          where m.clan_id::text = c.id::text
            and m.user_id = auth.uid()
            and m.role = '군주'
        )
      )
  )
);

drop policy if exists "distribution_payments_insert_manage" on public.clan_distribution_payments;
create policy "distribution_payments_insert_manage"
on public.clan_distribution_payments for insert to authenticated
with check (
  exists (
    select 1 from public.clans c
    where c.id::text = clan_distribution_payments.clan_id
      and (
        c.owner_user_id = auth.uid()
        or exists (
          select 1 from public.clan_members m
          where m.clan_id::text = c.id::text
            and m.user_id = auth.uid()
            and m.role = '군주'
        )
      )
  )
);

drop policy if exists "distribution_payments_update_manage" on public.clan_distribution_payments;
create policy "distribution_payments_update_manage"
on public.clan_distribution_payments for update to authenticated
using (
  exists (
    select 1 from public.clans c
    where c.id::text = clan_distribution_payments.clan_id
      and (
        c.owner_user_id = auth.uid()
        or exists (
          select 1 from public.clan_members m
          where m.clan_id::text = c.id::text
            and m.user_id = auth.uid()
            and m.role = '군주'
        )
      )
  )
)
with check (
  exists (
    select 1 from public.clans c
    where c.id::text = clan_distribution_payments.clan_id
      and (
        c.owner_user_id = auth.uid()
        or exists (
          select 1 from public.clan_members m
          where m.clan_id::text = c.id::text
            and m.user_id = auth.uid()
            and m.role = '군주'
        )
      )
  )
);

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime'
      and schemaname='public'
      and tablename='clan_distribution_payments'
  ) then
    execute 'alter publication supabase_realtime add table public.clan_distribution_payments';
  end if;
end $$;

notify pgrst, 'reload schema';
